FROM quay.io/podman/stable:latest

LABEL maintainer="Caseraw"
LABEL description="Custom podman build for developming Ansible content."

RUN dnf install -y \
  python3-pip \
  podman \
  skopeo \
  buildah \
  openssh \
  openssh-clients \
  vim \
  git \
  curl \
  wget \
  jq \
  bash-completion &&\
  dnf clean all &&\
  rm -rf /var/cache/{dnf,yum} &&\
  rm -rf /var/lib/dnf/history.* &&\
  rm -rf /var/log/*

USER podman
ENV PATH="$HOME/.local/bin:/config/.local/bin:$PATH"

RUN pip3 install --user --upgrade \
  pip \
  setuptools \
  ansible \
  ansible-navigator \
  ansible-builder &&\
  mkdir ~/project

WORKDIR /home/podman/project